steps:
    - id: "Building image using Dockerfile"
      name: 'gcr.io/cloud-builders/docker'
      args: ['build','-t','gcr.io/$PROJECT_ID/app-go-web:$SHORT_SHA','-f','dockerfile','.']

    - id: "Pushing image"
      name: 'gcr.io/cloud-builders/docker'
      args: ['push','gcr.io/$PROJECT_ID/app-go-web:$SHORT_SHA']

    - id: "Adjusting deployment file - K8s"
      name: 'gcr.io/cloud-builders/gcloud'
      entrypoint: '/bin/sh'
      args:
        - '-c'
        - |
          sed 's#img-app-deployment#gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA#g' k8s/deployment.yaml > k8s/deployment-new.yaml;
          cat k8s/deployment-new.yaml;

    - id: "Deployng k8s"
      name: 'gcr.io/cloud-builders/kubectl'
      args:
        - 'apply'
        - '-f'
        - 'k8s/deployment-new.yaml'
      env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel' 